symfonycasts_reset_password:
    request_password_repository: App\Repository\RequestResetPasswordRepository
    lifetime: '%env(int:LIFETIME_RESET_PASSWORD)%'
    #throttle_limit: 3600
    #enable_garbage_collection: true