framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: '%app.fallbacks%'
        providers:
           loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['Messages']
                locales: '%app.locales%'