twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/Partials/Bootstrap': Bootstrap
        '%kernel.project_dir%/templates/Partials': Default
    file_name_pattern: '*.twig'
    globals:
        locales: '%app.locales%'

when@test:
    twig:
        strict_variables: true
