# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Langage Parameters
    app.locales:            [de, en, es, fr, it, ja, th]
    app.fallbacks:          [en, fr, ja, de, es, it, th, ar]
    app.supported_locales:  '%app.locales%'
    app.default_locale:     '%kernel.default_locale%'
    # Global Path Parameters
    Path.Upload:            '%kernel.project_dir%/files/Uploads'
    Path.Download:          '%kernel.project_dir%/files/Downloads'
    Path.Gallery:           '%Path.Upload%/Gallery'
    # Path Parameters
    Path.D.App:             '%Path.Download%/Applications'
    Path.D.Source:          '%Path.Download%/Sources'
    Path.U.Forum:           '%Path.Upload%/Forums'
    Path.U.User:            '%Path.Upload%/Users'
    Path.U.G.Image:         '%Path.Gallery%/Images'
    Path.U.G.Video:         '%Path.Gallery%/Videos'
    Path.U.G.User:          '%Path.Gallery%/Users'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $defaultLocale: 'en'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
              
    # Register the UserStatusService
    App\Service\UserStatusService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Register the UserLocationService
    App\Service\UserLocationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: 'en'
        tags:
            - { name: 'kernel.event_subscriber' }

    # Register the event listener for user location
    #App\EventListener\UserLocationListener:
    #    tags:
    #        - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController' }